#! /bin/bash

STEEL_RAIN_PROTON_ROOT=/home/mick/latest/qpid-proton
STEEL_RAIN_PROTON_INSTALL=/home/mick/latest/qpid-proton/install


for client in send direct receive
do
  echo " "
  echo "   compile ${client}..."
  /usr/bin/cc  -I${STEEL_RAIN_PROTON_ROOT}/c/include \
               -I${STEEL_RAIN_PROTON_ROOT}/c/src     \
               -I${STEEL_RAIN_PROTON_ROOT}/build/c/include \
               -I${STEEL_RAIN_PROTON_ROOT}/build/c/src \
               -fvisibility=hidden -O2    \
               -DNDEBUG -std=c99 -MD -MT  \
               ./${client}.c.o -MF ./${client}.c.o.d \
               -o ./${client}.c.o \
               -c ./${client}.c

  echo "   link ${client}"
  /usr/bin/cc  -fvisibility=hidden -O2 -g \
               -DNDEBUG -rdynamic         \
               ./${client}.c.o -o ${client}  \
               -Wl,-rpath,${STEEL_RAIN_PROTON_ROOT}/build/c \
               ${STEEL_RAIN_PROTON_INSTALL}/lib64/libqpid-proton-proactor.so \
               ${STEEL_RAIN_PROTON_INSTALL}/lib64/libqpid-proton-core.so \
               -lpthread
done


