#! /bin/bash

go run ./send.go         \
         -host=127.0.0.1 \
         -n_messages=100 \
         -n_sessions=5   \
         -throttle=100   \
         -addrs="addr_1 addr_2 addr_3 addr_4 addr_5"

